# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  projectName: bookgraphql
  registryServerName: '$(registryName).azurecr.io'
  imageName: '$(projectName)'
  # define 3 more variables: registryName, registryLogin and registryPassword in the build pipeline in UI

steps:
- script: docker build  --tag=$(registryServerName)/$(imageName):$(build.buildId) .
  displayName: 'docker build'

- script: |
    docker login $(registryServerName) -u $(registryLogin) -p $(registryPassword)
    docker push $(registryServerName)/$(imageName):$(build.buildId)
  displayName: 'docker push'
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))


- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
